/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.pkg01;
import java.util.Timer;
import java.util.TimerTask;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.Random;
import javax.swing.table.DefaultTableModel;
import java.lang.*;

/**
 *
 * @author Sarthak
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        
         TimerTask task = new TimerTask() {
      @Override
      public void run() {
        //SECRET ALGORITHM GOES HERE
        
        try{
            Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost/project","root","admin");
            Statement stmt= con.createStatement();
            int i=1;
            for(;i<=15;i++)
            {
            java.util.Random x = new java.util.Random();
            int n = 1 + x.nextInt(99);
            double kk=(double)n/1000;
            if(n>50){
            String query="Update stocks set value=value + (value*"+kk+") where sno="+i+";";
            stmt.executeUpdate(query);}
            else
            {String query1="Update stocks set value=value - (value*"+kk+") where sno="+i+";";
            stmt.executeUpdate(query1);}
            
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
      }
    };
    
    Timer timer = new Timer();
    long delay = 0;
    long intervalPeriod = 10 * 1000; 
    timer.scheduleAtFixedRate(task, delay,
                                intervalPeriod);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mon = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        usr = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Money");

        mon.setEditable(false);
        mon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monActionPerformed(evt);
            }
        });

        t1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rank", "Stock Name", "Value", "Owned"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(t1);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Buy");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Sell");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setText("User");

        usr.setEditable(false);
        usr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usr, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mon, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(mon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(usr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(49, 49, 49)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void monActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            DefaultTableModel model=(DefaultTableModel)t1.getModel();
            Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost/project","root","admin");
            Statement stmt= con.createStatement();
            
            String query="Select*from stocks;";
            
            ResultSet rs=stmt.executeQuery(query);
            model.setRowCount(0);
            int kkk=1;
            while(rs.next())
            {
                String v=rs.getString("value");
                String sn=rs.getString("stockname");
                
                model.addRow(new Object[]{kkk,sn,v});
                kkk++;
               }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        try{
          DefaultTableModel model=(DefaultTableModel)t1.getModel();
            Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost/project","root","admin");
            Statement stmt= con.createStatement();
            String user=usr.getText();
            String query2="Select*from account where username="+"'"+user+"'"+";";
            ResultSet rs1=stmt.executeQuery(query2);
            while(rs1.next())
            {
                int a1=rs1.getInt("a");model.setValueAt(a1, 0, 3);
                int b1=rs1.getInt("b");model.setValueAt(b1, 1, 3);
                int c1=rs1.getInt("c");model.setValueAt(c1, 2, 3);
                int d1=rs1.getInt("d");model.setValueAt(d1, 3, 3);
                int e1=rs1.getInt("e");model.setValueAt(e1, 4, 3);
                int f1=rs1.getInt("f");model.setValueAt(f1, 5, 3);
                int g1=rs1.getInt("g");model.setValueAt(g1, 6, 3);
                int h1=rs1.getInt("h");model.setValueAt(h1, 7, 3);
                int i1=rs1.getInt("i");model.setValueAt(i1, 8, 3);
                int j1=rs1.getInt("j");model.setValueAt(j1, 9,3);
                int k1=rs1.getInt("k");model.setValueAt(k1, 10, 3);
                int l1=rs1.getInt("l");model.setValueAt(l1, 11, 3);
                int m1=rs1.getInt("m");model.setValueAt(m1, 12, 3);
                int n1=rs1.getInt("n");model.setValueAt(n1, 13, 3);
                int o1=rs1.getInt("o");model.setValueAt(o1, 14, 3);
                
            }
        }
        
        
        
        catch(Exception e1){
            JOptionPane.showMessageDialog(null,e1);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            DefaultTableModel model=(DefaultTableModel)t1.getModel();
            Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost/project","root","admin");
            Statement stmt= con.createStatement();
            double mn=Double.parseDouble(mon.getText());
            String u=usr.getText();
            int x=t1.getSelectedRow();

            Object y=model.getValueAt(x,3);
            Object z=model.getValueAt(x,2);
            double value=Double.parseDouble((String) z);
            int l=(int)y;
            if(l>0)
            {  String kul;
            x=x+1;
                switch (x) {
                    case 1:
                        kul="a";
                        break;
                    case 2:
                        kul="b";
                        break;
                    case 3:
                        kul="c";
                        break;
                    case 4:
                        kul="d";
                        break;
                    case 5:
                        kul="e";
                        break;
                    case 6:
                        kul="f";
                        break;
                    case 7:
                        kul="g";
                        break;
                    case 8:
                        kul="h";
                        break;
                    case 9:
                        kul="i";
                        break;
                    case 10:
                        kul="j";
                        break;
                    case 11:
                        kul="k";
                        break;
                    case 12:
                        kul="l";
                        break;
                    case 13:
                        kul="m";
                        break;
                    case 14:
                        kul="n";
                        break;
                    case 15:
                        kul="o";
                        break;
                    default:
                        kul="ok";
                        break;
                }
                mn=mn+value;
                mn=Math.round(mn*100)/100;
                mon.setText(""+mn);
            String query="Update account set money ="+mn+" where username='"+u+"';";
            String query1="Update account set "+kul+"="+kul+"-1"+" where username='"+u+"';";
            stmt.executeUpdate(query);
            stmt.executeUpdate(query1);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        try{
            DefaultTableModel model=(DefaultTableModel)t1.getModel();
            Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost/project","root","admin");
            Statement stmt= con.createStatement();
            
            String query="Select*from stocks;";
            
            ResultSet rs=stmt.executeQuery(query);
            model.setRowCount(0);
            int kkk=1;
            while(rs.next())
            {
                String v=rs.getString("value");
                String sn=rs.getString("stockname");
                
                model.addRow(new Object[]{kkk,sn,v});
                kkk++;
               }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        try{
          DefaultTableModel model=(DefaultTableModel)t1.getModel();
            Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost/project","root","admin");
            Statement stmt= con.createStatement();
            String user=usr.getText();
            String query2="Select*from account where username="+"'"+user+"'"+";";
            ResultSet rs1=stmt.executeQuery(query2);
            while(rs1.next())
            {
                int a1=rs1.getInt("a");model.setValueAt(a1, 0, 3);
                int b1=rs1.getInt("b");model.setValueAt(b1, 1, 3);
                int c1=rs1.getInt("c");model.setValueAt(c1, 2, 3);
                int d1=rs1.getInt("d");model.setValueAt(d1, 3, 3);
                int e1=rs1.getInt("e");model.setValueAt(e1, 4, 3);
                int f1=rs1.getInt("f");model.setValueAt(f1, 5, 3);
                int g1=rs1.getInt("g");model.setValueAt(g1, 6, 3);
                int h1=rs1.getInt("h");model.setValueAt(h1, 7, 3);
                int i1=rs1.getInt("i");model.setValueAt(i1, 8, 3);
                int j1=rs1.getInt("j");model.setValueAt(j1, 9,3);
                int k1=rs1.getInt("k");model.setValueAt(k1, 10, 3);
                int l1=rs1.getInt("l");model.setValueAt(l1, 11, 3);
                int m1=rs1.getInt("m");model.setValueAt(m1, 12, 3);
                int n1=rs1.getInt("n");model.setValueAt(n1, 13, 3);
                int o1=rs1.getInt("o");model.setValueAt(o1, 14, 3);
                
            }
        }
        
        
        
        catch(Exception e1){
            JOptionPane.showMessageDialog(null,e1);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void usrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usrActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            DefaultTableModel model=(DefaultTableModel)t1.getModel();
            Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost/project","root","admin");
            Statement stmt= con.createStatement();
            double mn=Double.parseDouble(mon.getText());
            String u=usr.getText();
            int x=t1.getSelectedRow();

          
            Object z=model.getValueAt(x,2);
           
            double value=Double.parseDouble((String) z);
            
            if(mn>=value)
            {  String kul;
            x=x+1;
                switch (x) {
                    case 1:
                        kul="a";
                        break;
                    case 2:
                        kul="b";
                        break;
                    case 3:
                        kul="c";
                        break;
                    case 4:
                        kul="d";
                        break;
                    case 5:
                        kul="e";
                        break;
                    case 6:
                        kul="f";
                        break;
                    case 7:
                        kul="g";
                        break;
                    case 8:
                        kul="h";
                        break;
                    case 9:
                        kul="i";
                        break;
                    case 10:
                        kul="j";
                        break;
                    case 11:
                        kul="k";
                        break;
                    case 12:
                        kul="l";
                        break;
                    case 13:
                        kul="m";
                        break;
                    case 14:
                        kul="n";
                        break;
                    case 15:
                        kul="o";
                        break;
                    default:
                        kul="ok";
                        break;
                }
                mn=mn-value;
                mn=Math.round(mn*100)/100;
                mon.setText(""+mn);
            String query="Update account set money ="+mn+" where username='"+u+"';";
            String query1="Update account set "+kul+"="+kul+"+1"+" where username='"+u+"';";
            stmt.executeUpdate(query);
            stmt.executeUpdate(query1);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        try{
            DefaultTableModel model=(DefaultTableModel)t1.getModel();
            Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost/project","root","admin");
            Statement stmt= con.createStatement();
            
            String query="Select*from stocks;";
            
            ResultSet rs=stmt.executeQuery(query);
            model.setRowCount(0);
            int kkk=1;
            while(rs.next())
            {
                String v=rs.getString("value");
                String sn=rs.getString("stockname");
                
                model.addRow(new Object[]{kkk,sn,v});
                kkk++;
               }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        try{
          DefaultTableModel model=(DefaultTableModel)t1.getModel();
            Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost/project","root","admin");
            Statement stmt= con.createStatement();
            String user=usr.getText();
            String query2="Select*from account where username="+"'"+user+"'"+";";
            ResultSet rs1=stmt.executeQuery(query2);
            while(rs1.next())
            {
                int a1=rs1.getInt("a");model.setValueAt(a1, 0, 3);
                int b1=rs1.getInt("b");model.setValueAt(b1, 1, 3);
                int c1=rs1.getInt("c");model.setValueAt(c1, 2, 3);
                int d1=rs1.getInt("d");model.setValueAt(d1, 3, 3);
                int e1=rs1.getInt("e");model.setValueAt(e1, 4, 3);
                int f1=rs1.getInt("f");model.setValueAt(f1, 5, 3);
                int g1=rs1.getInt("g");model.setValueAt(g1, 6, 3);
                int h1=rs1.getInt("h");model.setValueAt(h1, 7, 3);
                int i1=rs1.getInt("i");model.setValueAt(i1, 8, 3);
                int j1=rs1.getInt("j");model.setValueAt(j1, 9,3);
                int k1=rs1.getInt("k");model.setValueAt(k1, 10, 3);
                int l1=rs1.getInt("l");model.setValueAt(l1, 11, 3);
                int m1=rs1.getInt("m");model.setValueAt(m1, 12, 3);
                int n1=rs1.getInt("n");model.setValueAt(n1, 13, 3);
                int o1=rs1.getInt("o");model.setValueAt(o1, 14, 3);
                
            }
        }
        
        
        
        catch(Exception e1){
            JOptionPane.showMessageDialog(null,e1);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        double m; 
        m = Double.parseDouble(mon.getText());
        String u=usr.getText();
        
        IndexFrame inf= new IndexFrame();
        inf.setVisible(true);
        MainFrame mf= new MainFrame();
        mf.setVisible(false);
        inf.mon.setText(""+m);
        inf.usr.setText(""+u);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField mon;
    private javax.swing.JTable t1;
    public static javax.swing.JTextField usr;
    // End of variables declaration//GEN-END:variables
}
